name: OFW CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v2
      - name: Testing OFW with g++
        uses: ./.github/actions/run_tests
        with:
          compiler: 'g++-10'

  clang:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v2
      - name: Testing OFW with clang
        uses: ./.github/actions/run_tests
        with:
          compiler: 'clang++-10'
